name: "comal graph"
channel_size: 1024
graph {
  name: "X=ss01,B=ss01,C=ss10,d=s0"
  operators {
    name: "fiberlookup"
    id: 2
    fiber_lookup {
      output_ref {
        id {
          id: 1
        }
      }
      output_crd {
        id {
          id: 2
        }
      }
      index: "j"
      tensor: "B"
      format: "compressed"
      src: true
      root: true
      label: "FiberLookup j: B0\\ncompressed"
    }
  }
  operators {
    name: "repsiggen"
    id: 3
    repeatsig {
      input_crd {
        id {
          id: 30
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 3
        }
      }
      label: "RepeatSignalGenerator j"
      index: "j"
    }
  }
  operators {
    name: "repeat"
    id: 4
    repeat {
      output_ref {
        id {
          id: 4
        }
      }
      input_rep_sig {
        id {
          id: 3
        }
        name: "repsig"
      }
      label: "Repeat j: C"
      index: "j"
      root: true
      tensor: "C"
    }
  }
  operators {
    name: "fiberlookup"
    id: 5
    fiber_lookup {
      input_ref {
        id {
          id: 4
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 5
        }
      }
      output_crd {
        id {
          id: 6
        }
      }
      index: "k"
      tensor: "C"
      mode: 1
      format: "compressed"
      src: true
      label: "FiberLookup k: C1\\ncompressed"
    }
  }
  operators {
    name: "repsiggen"
    id: 6
    repeatsig {
      input_crd {
        id {
          id: 34
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 7
        }
      }
      label: "RepeatSignalGenerator k"
      index: "k"
    }
  }
  operators {
    name: "repeat"
    id: 7
    repeat {
      input_ref {
        id {
          id: 32
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 8
        }
      }
      input_rep_sig {
        id {
          id: 7
        }
        name: "repsig"
      }
      label: "Repeat k: B"
      index: "k"
      tensor: "B"
    }
  }
  operators {
    name: "fiberlookup"
    id: 8
    fiber_lookup {
      input_ref {
        id {
          id: 5
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 9
        }
      }
      output_crd {
        id {
          id: 10
        }
        name: "in-C"
      }
      index: "l"
      tensor: "C"
      format: "compressed"
      src: true
      label: "FiberLookup l: C0\\ncompressed"
    }
  }
  operators {
    name: "fiberlookup"
    id: 9
    fiber_lookup {
      input_ref {
        id {
          id: 8
        }
        name: "ref"
      }
      output_ref {
        id {
          id: 11
        }
      }
      output_crd {
        id {
          id: 12
        }
        name: "in-B"
      }
      index: "l"
      tensor: "B"
      mode: 1
      format: "compressed"
      src: true
      label: "FiberLookup l: B1\\ncompressed"
    }
  }
  operators {
    name: "intersect"
    id: 10
    joiner {
      input_pairs {
        crd {
          id {
            id: 12
          }
          name: "crd_in-B"
        }
        ref {
          id {
            id: 11
          }
          name: "ref_in-B"
        }
      }
      input_pairs {
        crd {
          id {
            id: 10
          }
          name: "crd_in-C"
        }
        ref {
          id {
            id: 9
          }
          name: "ref_in-C"
        }
      }
      index: "l"
      label: "intersect l"
      output_ref1 {
        id {
          id: 13
        }
        name: "out-B"
      }
      output_ref2 {
        id {
          id: 14
        }
        name: "out-C"
      }
      output_crd {
        id {
        }
        name: "in-l"
      }
    }
  }
  operators {
    name: "arrayvals"
    id: 13
    array {
      tensor: "C"
      input_ref {
        id {
          id: 14
        }
        name: "ref_out-C"
      }
      output_val {
        id {
          id: 16
        }
        name: "val"
      }
      label: "Array Vals: C"
    }
  }
  operators {
    name: "arrayvals"
    id: 14
    array {
      tensor: "B"
      input_ref {
        id {
          id: 13
        }
        name: "ref_out-B"
      }
      output_val {
        id {
          id: 17
        }
        name: "val"
      }
      label: "Array Vals: B"
    }
  }
  operators {
    name: "mul"
    id: 15
    alu {
      vals {
        inputs {
          id {
            id: 17
          }
          name: "val"
        }
        inputs {
          id {
            id: 16
          }
          name: "val"
        }
        output {
          id {
            id: 18
          }
          name: "val"
        }
      }
      stages {
        inputs: 0
        inputs: 1
        op: MUL
      }
      label: "Mul"
    }
  }
  operators {
    name: "reduce"
    id: 16
    reduce {
      input_val {
        id {
          id: 18
        }
        name: "val"
      }
      output_val {
        id {
          id: 19
        }
        name: "reduce_val"
      }
    }
  }
  operators {
    name: "fiberlookup"
    id: 20
    fiber_lookup {
      output_ref {
        id {
          id: 20
        }
      }
      output_crd {
        id {
          id: 21
        }
        name: "in-d"
      }
      index: "j"
      tensor: "d"
      format: "compressed"
      src: true
      root: true
      label: "FiberLookup j: d0\\ncompressed"
    }
  }
  operators {
    name: "union"
    id: 22
    joiner {
      join_type: UNION
      input_pairs {
        crd {
          id {
            id: 31
          }
          name: "crd_in-A"
        }
        ref {
          id {
            id: 33
          }
          name: "ref_in-A"
        }
      }
      input_pairs {
        crd {
          id {
            id: 21
          }
          name: "crd_in-d"
        }
        ref {
          id {
            id: 20
          }
          name: "ref_in-d"
        }
      }
      index: "j"
      label: "union j"
      output_ref1 {
        id {
        }
        name: "out-A"
      }
      output_ref2 {
        id {
          id: 23
        }
        name: "out-d"
      }
      output_crd {
        id {
          id: 24
        }
      }
    }
  }
  operators {
    name: "repsiggen"
    id: 24
    repeatsig {
      input_crd {
        id {
          id: 35
        }
        name: "crd"
      }
      output_rep_sig {
        id {
          id: 25
        }
      }
      label: "RepeatSignalGenerator k"
      index: "k"
    }
  }
  operators {
    name: "repeat"
    id: 25
    repeat {
      input_ref {
        id {
          id: 23
        }
        name: "ref_out-d"
      }
      output_ref {
        id {
          id: 26
        }
      }
      input_rep_sig {
        id {
          id: 25
        }
        name: "repsig"
      }
      label: "Repeat k: d"
      index: "k"
      tensor: "d"
    }
  }
  operators {
    name: "arrayvals"
    id: 26
    array {
      tensor: "d"
      input_ref {
        id {
          id: 26
        }
        name: "ref"
      }
      output_val {
        id {
          id: 27
        }
        name: "val"
      }
      label: "Array Vals: d"
    }
  }
  operators {
    name: "add"
    id: 28
    alu {
      vals {
        inputs {
          id {
            id: 27
          }
          name: "val"
        }
        inputs {
          id {
            id: 19
          }
          name: "val"
        }
        output {
          id {
            id: 28
          }
          name: "val"
        }
      }
      stages {
        inputs: 0
        inputs: 1
      }
      label: "Add"
    }
  }
  operators {
    name: "fiberwrite"
    id: 29
    fiber_write {
      input_crd {
        id {
          id: 24
        }
        name: "crd"
      }
      index: "j"
      tensor: "X"
      format: "compressed"
      segsize: "2"
      crdsize: "A0_dim"
      sink: true
      label: "FiberWrite j: X0\\ncompressed"
    }
  }
  operators {
    name: "fiberwrite"
    id: 30
    fiber_write {
      input_crd {
        id {
          id: 36
        }
        name: "crd"
      }
      index: "k"
      tensor: "X"
      format: "compressed"
      segsize: "A0_dim+1"
      crdsize: "A0_dim*A1_dim"
      sink: true
      label: "FiberWrite k: X1\\ncompressed"
    }
  }
  operators {
    name: "valwrite"
    id: 31
    val_write {
      input_val {
        id {
          id: 28
        }
        name: "val"
      }
      label: "FiberWrite Vals: X"
      crdsize: "1*A0_dim*A1_dim"
      tensor: "X"
      sink: true
    }
  }
  operators {
    name: "broadcast"
    id: 32
    broadcast {
      crd {
        input {
          id {
            id: 2
          }
          name: "crd"
        }
        outputs {
          id {
            id: 30
          }
        }
        outputs {
          id {
            id: 31
          }
        }
      }
    }
  }
  operators {
    name: "broadcast"
    id: 33
    broadcast {
      ref {
        input {
          id {
            id: 1
          }
          name: "ref"
        }
        outputs {
          id {
            id: 32
          }
        }
        outputs {
          id {
            id: 33
          }
        }
      }
    }
  }
  operators {
    name: "broadcast"
    id: 34
    broadcast {
      crd {
        input {
          id {
            id: 6
          }
          name: "crd"
        }
        outputs {
          id {
            id: 34
          }
        }
        outputs {
          id {
            id: 35
          }
        }
        outputs {
          id {
            id: 36
          }
        }
      }
    }
  }
}
