name: "A=ss01,E=ss01,F=ss10,C=ss10,d=s0\""
operators {
  name: "fiberlookup"
  id: 41
  fiber_lookup {
    output_ref {
      id {
        id: 46
      }
    }
    output_crd {
      id {
        id: 45
      }
      name: "in-d"
    }
    index: "j"
    tensor: "d"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup j: d0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 40
  fiber_lookup {
    output_ref {
      id {
        id: 44
      }
    }
    output_crd {
      id {
        id: 1
      }
      name: "in-E"
    }
    index: "j"
    tensor: "E"
    format: "compressed"
    src: true
    root: true
    label: "FiberLookup j: E0\\ncompressed"
  }
}
operators {
  name: "union"
  id: 39
  joiner {
    join_type: UNION
    input_pairs {
      crd {
        id {
          id: 1
        }
        name: "crd_in-E"
      }
      ref {
        id {
          id: 44
        }
        name: "ref_in-E"
      }
    }
    input_pairs {
      crd {
        id {
          id: 45
        }
        name: "crd_in-d"
      }
      ref {
        id {
          id: 46
        }
        name: "ref_in-d"
      }
    }
    index: "j"
    label: "union j"
    output_ref1 {
      id {
        id: 41
      }
      name: "out-E"
    }
    output_ref2 {
      id {
        id: 42
      }
      name: "out-d"
    }
    output_crd {
      id {
        id: 2
      }
      name: "j"
    }
  }
}
operators {
  name: "repsiggen"
  id: 37
  repeatsig {
    input_crd {
      id {
        id: 2
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 5
      }
    }
    label: "RepeatSignalGenerator j"
    index: "j"
  }
}
operators {
  name: "repeat"
  id: 35
  repeat {
    output_ref {
      id {
        id: 34
      }
    }
    input_rep_sig {
      id {
        id: 5
      }
      name: "repsig"
    }
    label: "Repeat j: C"
    index: "j"
    root: true
    tensor: "C"
  }
}
operators {
  name: "repeat"
  id: 34
  repeat {
    output_ref {
      id {
        id: 6
      }
    }
    input_rep_sig {
      id {
        id: 5
      }
      name: "repsig"
    }
    label: "Repeat j: F"
    index: "j"
    root: true
    tensor: "F"
  }
}
operators {
  name: "fiberlookup"
  id: 33
  fiber_lookup {
    input_ref {
      id {
        id: 34
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 38
      }
    }
    output_crd {
      id {
        id: 35
      }
    }
    index: "k"
    tensor: "C"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup k: C1\\ncompressed"
  }
}
operators {
  name: "repsiggen"
  id: 31
  repeatsig {
    input_crd {
      id {
        id: 35
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 36
      }
    }
    label: "RepeatSignalGenerator k"
    index: "k"
  }
}
operators {
  name: "repeat"
  id: 29
  repeat {
    input_ref {
      id {
        id: 6
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 7
      }
    }
    input_rep_sig {
      id {
        id: 36
      }
      name: "repsig"
    }
    label: "Repeat k: F"
    index: "k"
    tensor: "F"
  }
}
operators {
  name: "repeat"
  id: 28
  repeat {
    input_ref {
      id {
        id: 41
      }
      name: "ref_out-E"
    }
    output_ref {
      id {
        id: 37
      }
    }
    input_rep_sig {
      id {
        id: 36
      }
      name: "repsig"
    }
    label: "Repeat k: E"
    index: "k"
    tensor: "E"
  }
}
operators {
  name: "fiberlookup"
  id: 27
  fiber_lookup {
    input_ref {
      id {
        id: 38
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 40
      }
    }
    output_crd {
      id {
        id: 39
      }
      name: "in-C"
    }
    index: "l"
    tensor: "C"
    format: "compressed"
    src: true
    label: "FiberLookup l: C0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 26
  fiber_lookup {
    input_ref {
      id {
        id: 7
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 33
      }
    }
    output_crd {
      id {
        id: 8
      }
      name: "in-F"
    }
    index: "l"
    tensor: "F"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup l: F1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 25
  joiner {
    input_pairs {
      crd {
        id {
          id: 8
        }
        name: "crd_in-F"
      }
      ref {
        id {
          id: 33
        }
        name: "ref_in-F"
      }
    }
    input_pairs {
      crd {
        id {
          id: 39
        }
        name: "crd_in-C"
      }
      ref {
        id {
          id: 40
        }
        name: "ref_in-C"
      }
    }
    index: "l"
    label: "intersect l"
    output_ref1 {
      id {
        id: 29
      }
      name: "out-F"
    }
    output_ref2 {
      id {
        id: 32
      }
      name: "out-C"
    }
    output_crd {
      id {
        id: 9
      }
      name: "l"
    }
  }
}
operators {
  name: "repsiggen"
  id: 23
  repeatsig {
    input_crd {
      id {
        id: 9
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 12
      }
    }
    label: "RepeatSignalGenerator l"
    index: "l"
  }
}
operators {
  name: "repeat"
  id: 22
  repeat {
    input_ref {
      id {
        id: 37
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 13
      }
    }
    input_rep_sig {
      id {
        id: 12
      }
      name: "repsig"
    }
    label: "Repeat l: E"
    index: "l"
    tensor: "E"
  }
}
operators {
  name: "fiberlookup"
  id: 21
  fiber_lookup {
    input_ref {
      id {
        id: 29
      }
      name: "ref_out-F"
    }
    output_ref {
      id {
        id: 31
      }
    }
    output_crd {
      id {
        id: 30
      }
      name: "in-F"
    }
    index: "i"
    tensor: "F"
    format: "compressed"
    src: true
    label: "FiberLookup i: F0\\ncompressed"
  }
}
operators {
  name: "fiberlookup"
  id: 20
  fiber_lookup {
    input_ref {
      id {
        id: 13
      }
      name: "ref"
    }
    output_ref {
      id {
        id: 28
      }
    }
    output_crd {
      id {
        id: 14
      }
      name: "in-E"
    }
    index: "i"
    tensor: "E"
    mode: 1
    format: "compressed"
    src: true
    label: "FiberLookup i: E1\\ncompressed"
  }
}
operators {
  name: "intersect"
  id: 19
  joiner {
    input_pairs {
      crd {
        id {
          id: 14
        }
        name: "crd_in-E"
      }
      ref {
        id {
          id: 28
        }
        name: "ref_in-E"
      }
    }
    input_pairs {
      crd {
        id {
          id: 30
        }
        name: "crd_in-F"
      }
      ref {
        id {
          id: 31
        }
        name: "ref_in-F"
      }
    }
    index: "i"
    label: "intersect i"
    output_ref1 {
      id {
        id: 23
      }
      name: "out-E"
    }
    output_ref2 {
      id {
        id: 26
      }
      name: "out-F"
    }
    output_crd {
      id {
        id: 15
      }
      name: "i"
    }
  }
}
operators {
  name: "repsiggen"
  id: 17
  repeatsig {
    input_crd {
      id {
        id: 15
      }
      name: "crd"
    }
    output_rep_sig {
      id {
        id: 16
      }
    }
    label: "RepeatSignalGenerator i"
    index: "i"
  }
}
operators {
  name: "repeat"
  id: 16
  repeat {
    input_ref {
      id {
        id: 32
      }
      name: "ref_out-C"
    }
    output_ref {
      id {
        id: 17
      }
    }
    input_rep_sig {
      id {
        id: 16
      }
      name: "repsig"
    }
    label: "Repeat i: C"
    index: "i"
    tensor: "C"
  }
}
operators {
  name: "crddrop"
  id: 15
  coord_drop {
    input_inner_crd {
      id {
        id: 15
      }
      name: "crd_i"
    }
    input_outer_crd {
      id {
        id: 9
      }
      name: "crd_l"
    }
    output_outer_crd {
      id {
        id: 10
      }
      name: "outer-l"
    }
    inner_crd: "i"
    outer_crd: "l"
    label: "CrdDrop l,i"
  }
}
operators {
  name: "crddrop"
  id: 14
  coord_drop {
    input_inner_crd {
      id {
        id: 10
      }
      name: "crd_outer-l"
    }
    input_outer_crd {
      id {
        id: 35
      }
      name: "crd_k"
    }
    output_outer_crd {
      id {
        id: 11
      }
      name: "outer-k"
    }
    inner_crd: "l"
    outer_crd: "k"
    label: "CrdDrop k,l"
  }
}
operators {
  name: "crddrop"
  id: 13
  coord_drop {
    input_inner_crd {
      id {
        id: 11
      }
      name: "crd_outer-k"
    }
    input_outer_crd {
      id {
        id: 2
      }
      name: "crd_j"
    }
    output_inner_crd {
      id {
        id: 4
      }
      name: "inner-k"
    }
    output_outer_crd {
      id {
        id: 3
      }
      name: "outer-j"
    }
    inner_crd: "k"
    outer_crd: "j"
    label: "CrdDrop j,k"
  }
}
operators {
  name: "arrayvals"
  id: 12
  array {
    tensor: "d"
    input_ref {
      id {
        id: 42
      }
      name: "ref_out-d"
    }
    output_val {
      id {
        id: 43
      }
      name: "val"
    }
    label: "Array Vals: d"
  }
}
operators {
  name: "arrayvals"
  id: 11
  array {
    tensor: "C"
    input_ref {
      id {
        id: 17
      }
      name: "ref"
    }
    output_val {
      id {
        id: 18
      }
      name: "val"
    }
    label: "Array Vals: C"
  }
}
operators {
  name: "arrayvals"
  id: 10
  array {
    tensor: "F"
    input_ref {
      id {
        id: 26
      }
      name: "ref_out-F"
    }
    output_val {
      id {
        id: 27
      }
      name: "val"
    }
    label: "Array Vals: F"
  }
}
operators {
  name: "arrayvals"
  id: 9
  array {
    tensor: "E"
    input_ref {
      id {
        id: 23
      }
      name: "ref_out-E"
    }
    output_val {
      id {
        id: 24
      }
      name: "val"
    }
    label: "Array Vals: E"
  }
}
operators {
  name: "mul"
  id: 8
  alu {
    vals {
      inputs {
        id {
          id: 24
        }
        name: "val"
      }
      inputs {
        id {
          id: 27
        }
        name: "val"
      }
      output {
        id {
          id: 25
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "mul"
  id: 7
  alu {
    vals {
      inputs {
        id {
          id: 18
        }
        name: "val"
      }
      inputs {
        id {
          id: 25
        }
        name: "val"
      }
      output {
        id {
          id: 19
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
      op: MUL
    }
    label: "Mul"
  }
}
operators {
  name: "reduce"
  id: 6
  reduce {
    input_val {
      id {
        id: 19
      }
      name: "val"
    }
    output_val {
      id {
        id: 20
      }
      name: "reduce_val"
    }
  }
}
operators {
  name: "reduce"
  id: 5
  reduce {
    input_val {
      id {
        id: 20
      }
      name: "val"
    }
    output_val {
      id {
        id: 21
      }
      name: "reduce_val"
    }
  }
}
operators {
  name: "add"
  id: 4
  alu {
    vals {
      inputs {
        id {
          id: 21
        }
        name: "val"
      }
      inputs {
        id {
          id: 43
        }
        name: "val"
      }
      output {
        id {
          id: 22
        }
        name: "val"
      }
    }
    stages {
      inputs: 0
      inputs: 1
    }
    label: "Add"
  }
}
operators {
  name: "fiberwrite"
  id: 3
  fiber_write {
    input_crd {
      id {
        id: 3
      }
      name: "crd_outer-j"
    }
    index: "j"
    tensor: "A"
    format: "compressed"
    segsize: "2"
    crdsize: "E0_dim"
    sink: true
    label: "FiberWrite j: A0\\ncompressed"
  }
}
operators {
  name: "fiberwrite"
  id: 2
  fiber_write {
    input_crd {
      id {
        id: 4
      }
      name: "crd_inner-k"
    }
    index: "k"
    tensor: "A"
    format: "compressed"
    segsize: "E0_dim+1"
    crdsize: "E0_dim*C1_dim"
    sink: true
    label: "FiberWrite k: A1\\ncompressed"
  }
}
operators {
  name: "valwrite"
  id: 1
  val_write {
    input_val {
      id {
        id: 22
      }
      name: "val"
    }
    label: "FiberWrite Vals: A"
    crdsize: "1*E0_dim*C1_dim"
    tensor: "A"
    sink: true
  }
}

