name: "SimpleProgram",
operators [
  {
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "i",
      tensor: "B",
      mode: 0,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    fiber_lookup: {
      output_ref {
        id: 9
      },
      output_crd {
        id: 9
      },
      index: "i",
      tensor: "C",
      mode: 0,
      format: "compressed",
      src: true,
      root: true,
    }
  },
  {
    fiber_write: {
        input_crd: { 
          id: 9 
        },
        index: "i",
        tensor: "X",
        mode: 0,
        format: "compressed",
        segsize: 2,
        sink: true,
    }
  }, 
  {
    broadcast: {
      input {
        id: 2
      },
      output{
        id: 3
      }
    }
  }
]